language: java

# clone "travis" branch containing deployment settings
before_install: git clone -b travis https://github.com/daisy-consortium/maven-parents.git target/travis

# main task, run the verify goal
script: mvn verify

# if the build succeeds, deploy the artifact (tests are skipped)
after_success: mvn deploy -DskipTests -Dinvoker.skip=true --settings target/travis/settings.xml

# whitelist; only deploy master branch
branches:
  only:
  - master

env:
  global:
    - secure: "WCefOzTNpsvd2hKYkTm2rk9QEkRPqGmro2aWq3K/fDyVJ8M9LCsRjhVsB0laPsP8BtQQIYBSI7rBgpNQmdAlIGrNzao+wHALYMqXa/laLIatcZoUbYHgCg/1GZX/Eq4Ycj6Ix2HNCv3xy3EpspqXhcp4WpS/tAfUiWi/6LZLc/A="
    - secure: "LorjDTVBc/A5OCohpjBl3an5CUCW9gI56YnIwkWip0w8tFLQ4WGyZF1bT+GGUFY4KExzmsfDk2EtvkTJp7UBLZAWG/TIraGeCM8jD5nqGGQnfBrC1PKZBJwxA2vuTWw890Af6oZGICg6k2oVdAkZUGhXahlShxolLHT6cwCCxAY="